### ISSUE TITLE
Add info about https://jitpack.io to readme

### ISSUE THREAD

**Issue by tonycox** [sbrannen/spring-test-junit5#10]

**Comment by sbrannen** [comment]
Thanks for the tip regarding JitPack! 👍 

I've updated the README accordingly.

Would you mind verifying that the new documentation regarding group ID, artifact ID, and version work for you when using JitPack?

**Comment by tonycox** [comment]
This works well. Thank you Sam

**Comment by sbrannen** [comment]
You're welcome!  And... thanks for the feedback.
