### ISSUE TITLE
No tests are run with junit-platform 1.2.0 and jupiter 5.2.0

### ISSUE THREAD

**Issue by whiskeysierra** [sbrannen/spring-test-junit5#16]
I tried to upgrade from junit-platform 1.0.3 and jupiter 5.0.3 to 1.2.0 and 5.2.0 respectively. See https://github.com/zalando/logbook/pull/262. But it looks like the extension no longer works. At least during my spring tests I see this:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project logbook-spring-boot-starter: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]
>
> https://travis-ci.org/zalando/logbook/jobs/379081016#L1972

**Comment by whiskeysierra** [comment]
An indicator why I believe the problem is with the SpringExtension can be seen here: https://travis-ci.org/zalando/logbook/builds/379081572

Running the same tests against spring boot 2 (+ spring 5) and using the official SpringExtension from Spring 5 (by disabling our junit5 profile), it works. Even with the newer JUnit/Jupiter versions.

**Comment by whiskeysierra** [comment]
Might be related to this, maybe? 


```xml
<!-- for some reason, this is needed to make spring-test-junit5 work -->
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-commons</artifactId>
    <version>${junit-platform.version}</version>
    <scope>test</scope>
</dependency>
```
https://github.com/zalando/logbook/blob/master/logbook-spring-boot-starter/pom.xml#L118

**Comment by sbrannen** [comment]
Please try [tag `1.2.0`](https://github.com/sbrannen/spring-test-junit5/releases/tag/1.2.0) and report back whether that works for you.

Thanks in advance!

**Comment by whiskeysierra** [comment]
Works! Thanks for the fast response! :tada:

**Comment by sbrannen** [comment]
You're welcome!

And thanks for letting me know the new tag works.
