### ISSUE TITLE
Disabling tests with SpEL

### ISSUE THREAD

**Issue by ttddyy** [sbrannen/spring-test-junit5#4]
Relates to this issue: https://github.com/junit-team/junit5/issues/219

`@DisabledIf("SpEL here")` may be handy as well.

**Comment by sbrannen** [comment]
@ttddyy, would you mind opening a ticket against Spring's official JIRA issue tracker for this request?

**Comment by ttddyy** [comment]
ok, just created jira ticket

https://jira.spring.io/browse/SPR-14614

I'll give a shot to implement this :)

**Comment by sbrannen** [comment]
Thanks!
