### ISSUE TITLE
Is it planned to upload this dependency to the maven central?

### ISSUE THREAD

**Issue by vchernogorov** [sbrannen/spring-test-junit5#7]

**Comment by sbrannen** [comment]
Spring's official support for JUnit 5 has already been released as part of the standard `spring-test` artifact in Spring Framework 5.0 milestones.

Thus, it is currently not planned to release the code in this repository as a stand-alone artifact.

However, having said that, the Spring team may consider releasing this as its own artifact or as a backport to Spring Framework 4.3.x depending on community interest.

Thus, if you're interested in using Spring's support for JUnit 5 outside of Spring 5.0, please feel free to open a ticket in [Spring's JIRA issue tracker](https://jira.spring.io/).

Cheers!
