### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by tonycox** [sbrannen/spring-test-junit5#9]
prototype-1 has too old dependencies

**Comment by sbrannen** [comment]
OK. I just created a tag for `1.0.0-M3` based on JUnit Jupiter 5.0.0-M3.

https://github.com/sbrannen/spring-test-junit5/releases/tag/1.0.0-M3

**Comment by sbrannen** [comment]
OK. I just created a tag for `1.0.0.M3` based on JUnit Jupiter 5.0.0-M3.

https://github.com/sbrannen/spring-test-junit5/releases/tag/1.0.0.M3
